{% set version = "2.2-0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pvclust
  version: {{ version|replace("-", "_") }}

source:
  fn: pvclust_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pvclust_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pvclust/pvclust_{{ version }}.tar.gz
  sha256: 7892853bacd413b5a921006429641ad308a344ca171b3081c15e4c522a8b0201

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('pvclust')"  # [not win]
    - "\"%R%\" -e \"library('pvclust')\""  # [win]

about:
  home: http://stat.sys.i.kyoto-u.ac.jp/prog/pvclust/
  license: GPL-2
  summary: An implementation of multiscale bootstrap resampling for assessing the uncertainty
    in hierarchical cluster analysis. It provides AU (approximately unbiased) p-value
    as well as BP (bootstrap probability) value for each cluster in a dendrogram.
  license_family: GPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero
